name: Deploy Pages
on:
  push: { branches: [ main ] }
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare static site from cleancasino_site
        run: |
          set -e
          mkdir -p site
          cp -R cleancasino_site/assets site/
          cp cleancasino_site/index.html site/
          cp cleancasino_site/about.html site/
          cp cleancasino_site/faq.html site/
          cp cleancasino_site/join.html site/
          # Вставляем base и адрес бэкенда на всех страницах
          for f in index.html about.html faq.html join.html; do
            # base href, чтобы ссылки и assets корректно работали под /cleancasino/
            sed -i '0,/<head>/s//<head>\n    <base href="\/cleancasino\/">/' site/$f
            # window.CC_API_BASE перед analytics.js
            sed -i 's|<script src="assets/js/analytics.js"></script>|<script>window.CC_API_BASE="https://cleancasino-backend.onrender.com";</script>\n    <script src="assets/js/analytics.js"></script>|' site/$f
          done

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
