services:
  - type: web
    name: cleancasino-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://holyneuron.github.io/cleancasino
      - key: DB_PATH
        value: /var/data/cleancasino.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
