name: Deploy Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare static site from cleancasino_site
        run: |
          mkdir -p site
          rsync -av --delete cleancasino_site/assets site/assets
          for f in index.html about.html faq.html join.html; do
            cp cleancasino_site/$f site/$f
            sed -i 's|<script src="assets/js/analytics.js"></script>|<script>window.CC_API_BASE="https://cleancasino-backend.onrender.com";</script>\n    <script src="assets/js/analytics.js"></script>|' site/$f
          done

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
